# If this is the first Google App Engine Service you are deploying,
# change 'modelserve' to 'default', since the first service must be
# named 'default'.

service: zenloopserve

runtime: python
env: flex

runtime_config:
    python_version: 3

entrypoint: gunicorn -b :$PORT main:app

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 20

readiness_check:
  check_interval_sec: 120
  timeout_sec: 40
  failure_threshold: 5
  success_threshold: 5
  app_start_timeout_sec: 3000

#endpoints_api_service:
#  name: modelserve-dot-PROJECT_ID.appspot.com
#  rollout_strategy: managed

env_variables:
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    SQLALCHEMY_DATABASE_URI: >-
     mysql+pymysql://USER:PASSWORD@/DATABASE?unix_socket=/cloudsql/INSTANCE_CONNECTION_NAME
    MODEL_BUCKET: zenloop_classifier
    CLASSIFIER_FILENAME: models/user_classifier.pkl
    ENC_FILENAME: dataset/encoded_fooditem.csv
    SIMILARITY_FILENAME: models/item_similarity.pkl

beta_settings:
      cloud_sql_instances: INSTANCE_CONNECTION_NAME

