swagger: "2.0"
info:
  title: "zenloopserve"
  description: "Get prediction from sklearn model."
  version: "1.0.0"
host: "zenloopserve-dot-PROJECT_ID.appspot.com"
#schemes:
#  - "https"
#security:
#  - api_key: []
#securityDefinitions:
#  api_key:
#    type: "apiKey"
#    name: "key"
#    in: "query"
paths:
  "/recommendFood":
#    post:
#      description: "Get recommendations for user."
#      operationId: "recommend"
#      consumes:
#      - "application/json"
#      produces:
#      - "application/json"
#      parameters:
#        -
#          name: "body"
#          in: "body"
#          required: true
#          schema:
#            $ref: "#/definitions/input"
#      responses:
#        200:
#          description: "Success."
#          schema:
#            $ref: "#/definitions/output"
#        400:
#          description: "Missing inputs."
#
#definitions:
#  input:
#    type: "json"
#    required:
#    - "input"
#    properties:
#       uname:
#        type: "string"
#      timeslot:
#        type: "string"
#        bglevel:
#          type: "number"
#          format: "float"
#        sugarConsumed:
#          type: "number"
#          format: "float"
#  output:
#    type: "json"
#    required:
#    - "output"
#    properties:
#      Breakfakt:
#        type: "array"
#      Lunch:
#        type: "array"
#      Dinner:
#        type: "array"